AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Omdena SurplusMap SAM Template for API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 2048

Resources:
  PowergridMapperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      FunctionName: powergrid-mapper
      Architectures:
        - x86_64
      Events:
        PowergridMapper:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /map
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: powergrid-mapper

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PowergridMapperApi:
    Description: "API Gateway endpoint URL for Prod stage for PowergridMapper function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/map/"
  PowergridMapperFunction:
    Description: "PowergridMapper Lambda Function ARN"
    Value: !GetAtt PowergridMapperFunction.Arn
  PowergridMapperFunctionIamRole:
    Description: "Implicit IAM Role created for PowergridMapper function"
    Value: !GetAtt PowergridMapperFunctionRole.Arn
