# This workflow will install Python dependencies and deploy to AWS Elastic Container Registry (ECR)

name: Deploy SAM

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Get Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - "api/models/**"
              - "api/**/*.py"
              - "api/**/*.yaml"
              - "api/**/*.toml"
              - "api/*.txt"
              - "api/Dockerfile"
            python:
              - "**/*.py"

      - name: Setup Python 3.8
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install dependencies
        if: steps.changes.outputs.api == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: SAM Deploy
        if: ${{ steps.filter.outputs.api == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        working-directory: ./api
        run: |
          sam build
          yes | sam deploy