# This workflow will install Python dependencies and deploy to AWS Elastic Container Registry (ECR)

name: Deploy SAM

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Get Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - "api/models/**"
              - "api/**/*.py"
              - "api/**/*.yaml"
              - "api/**/*.toml"
              - "api/*.txt"
              - "api/Dockerfile"
            python:
              - "**/*.py"

      - name: Setup Python 3.8
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Setup SAM
        if: steps.changes.outputs.api == 'true'
        uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS Credentials
        if: steps.changes.outputs.api == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: SAM Deploy
        if: steps.changes.outputs.api == 'true'
        working-directory: ./api
        run: |
          sam build
          sam deploy
