# This workflow will install Python dependencies, run tests and lint

name: Test Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Get Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - "api/models/**"
              - "api/**/*.py"
              - "api/**/*.yaml"
              - "api/**/*.toml"
              - "api/*.txt"
              - "api/Dockerfile"
            python:
              - "**/*.py"

      - name: Setup Python 3.8
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      
      - name: Install dependencies
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Lint
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        run: |
          flake8 ${{ steps.changes.outputs.python_files }}
      
      - name: Run Tests
        if: steps.changes.outputs.python == 'true' || steps.changes.outputs.api == 'true'
        working-directory: ./api
        run: |
          python -m pytest ./tests -r A
